build: generate-docker-script: Use os.environ to get required env vars
Fix the following type check failures:

  hack/build/generate-docker-script.py:459: error: Argument "kernel_version" to "generate_builds" has incompatible type "str | None"; expected "str"  [arg-type]
  hack/build/generate-docker-script.py:460: error: Argument "kernel_flavor" to "generate_builds" has incompatible type "str | None"; expected "str"  [arg-type]
  hack/build/generate-docker-script.py:461: error: Argument "kernel_src_url" to "generate_builds" has incompatible type "str | None"; expected "str"  [arg-type]
  hack/build/generate-docker-script.py:464: error: Argument "firmware_url" to "generate_builds" has incompatible type "str | None"; expected "str"  [arg-type]
  hack/build/generate-docker-script.py:465: error: Argument "firmware_sig_url" to "generate_builds" has incompatible type "str | None"; expected "str"  [arg-type]